---
extends:
  - airbnb
  - prettier
  - prettier/react

plugins:
  - html
  - prettier
  - react

parser: babel-eslint

parserOptions:
  ecmaVersion: 10
  ecmaFeatures:
    impliedStrict: true
    classes: true

env:
  browser: true
  jest: true
  node: true

globals: {}

rules:
  # general
  prefer-const: error
  radix:
    - error
    - as-needed
  comma-dangle: off
  consistent-return: off
  func-names: off
  max-len: off
  no-underscore-dangle: off
  no-unused-expressions:
    - error
    - allowTaggedTemplates: true
  no-unused-vars:
    - error
    - args: none
  no-shadow: error
  space-before-function-paren: off

  # debugging
  no-alert: warn
  no-debugger: warn
  no-console: warn

  # import
  import/extensions:
    - error
    - always
    - js: never
      jsx: never
  import/prefer-default-export: off

  # react
  react/prop-types: off
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react/display-name: warn
  react/no-array-index-key: off
  react/no-danger: off
  react/react-in-jsx-scope: off
  react/prefer-stateless-function: off
  react/forbid-prop-types: off
  react/no-unescaped-entities: off
  react/require-default-props: off
  react/jsx-filename-extension:
    - warn
    - extensions:
        - .js
        - .jsx

  # prettier
  prettier/prettier: error
