# Global settings applied to the whole site.  
# 
# “base” is the directory to change to before starting build. If you set base:
#        that is where we will look for package.json/.nvmrc/etc, not repo root!
# “command” is your build command.
# “publish” is the directory to publish (relative to the root of your repo).

[build]
  base    = ""
  publish = "public/"
  command = "gatsby build"

# Specific branch context: Deploys from this branch
# will take these settings and override their
# current ones.
[context.conway]
  command = "make feature"
  
