version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11-browsers

    working_directory: ~/site

    steps:
      - checkout

      - restore_cache:
          name: Restore cache
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install node modules
          command: npm install

      - save_cache:
          name: Save cache
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: npm run test
